name: Cleanup Github Pages

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Remove preview branch from gh-pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
          cd gh-pages
          git rm -r ${{ github.event.pull_request.head.ref }}
          git commit -m "Remove preview for ${{ github.event.pull_request.head.ref }}"
          git push origin gh-pages
